// Language content dictionary
export const translations = {
    en: {
        title: "Pet Merge",
        loading: "Loading",
        high_score: "High Score",
        play: "PLAY",
        classic: "Classic",
        adventure: "Adventure",
        coming_soon: "Coming Soon",
        unlock_level: "Unlock Level <X>",
        star_jar: "Star Jar",
        desc_star_jar: "Win levels to earn stars and unlock the jar!",
        full: "FULL!",
        rewards: "REWARDS!",
        open: "OPEN",
        claim: "Claim",
        tuto_tap_anywhere: "Tap to Continue",
        tuto_control: ["Drag","to Move","\n Release","to Drop"],
        tuto_adv: ["Reach", "the goal", "within", "the move limit"],
        tuto_adv_1: ["Drop", "tiles to", "Push", "others around"],
        level: "Level <X>",
        level_short : "Level",
        moves: "Moves",
        goals: "Goals",
        great: "GREAT",
        completed: "COMPLETED!",
        victory: "VICTORY!",
        continue: "Continue",
        continue_question: "CONTINUE?",
        get_moves: "Get 15 Moves",
        level_failed: "LEVEL FAILED",
        retry: "Retry",
        home: "Home",
        hammer_booster: "Hammer Booster",
        shake_booster: "Shake Booster",
        tornado_booster: "Tornado Booster",
        brush_booster: "Brush Booster",
        rainbow_booster: "Rainbow Booster",
        wood_box: "Wood Box",
        dessert_box: "Dessert Box",
        ice_box: "Ice Box",
        mystery_box: "Mystery Box",
        unlocked: "Unlocked!",
        tuto_hammer_unlocked: ["Hammer Booster", "Unlocked!", "Tap to Select Hammer"],
        tuto_hammer_unlocked_1: ["Hard Level", "Unlocked!", "Use", "Hammer", "to Clear Level Easier"],
        hammer: "Hammer",
        booster: "Booster",
        hammer_info_1: "Tap an Animal or Props to Remove it",
        hammer_info_2: "Remove an Animal or Props",
        hammer_info_3: "There's nothing to clear with hammer",
        tuto_tornado_unlocked: ["Tornado Booster", "Unlocked!", "Tap to start the Tornado"],
        tornado: "Tornado",
        start: "Start!",
        tornado_info_1: "Merge Animals with Tornado",
        tornado_info_2: "Use Tornado to Merge Animals!",
        tornado_info_3: "There's no tile inside the box",
        tuto_shake_unlocked: ["Shake Booster", "Unlocked!", "Tap to Shake the Basket"],
        shake: "Shake",
        shake_info_1: "Shake all animals and objects",
        shake_info_2: "Shake the Box for more merges!",
        shake_info_3: "There's no tile inside the box",
        tuto_rainbow_unlocked: ["Rainbow Booster", "Unlocked!", "Tap to Select Rainbow"],
        rainbow: "Rainbow",
        rainbow_info_1: "Drop rainbow to grow any animal",
        tuto_wood_box: ["Merge", "next", "to        ", "to", "Break", "it"],
        wood_box_info_1: "Merge next to the Wood Box to break it",
        tuto_dessert_box: ["Merge", "next", "to a Dessert Box", "to", "Break", "it"],
        dessert_box_info_1: "Merge next to the Dessert Box to break it",
        tuto_ice_box: ["Merge", "next", "to an Ice Box", "to", "Free", "the Animal"],
        ice_box_info_1: "Merge next to an Ice Box to Free the Animal inside",
        mystery_box_info_1: "Merge next to the Mystery Box to show the Animal Inside",
        level_up: "LEVEL UP",
        ok: "OK",
        tuto_brush_unlocked: ["Brush Booster", "Unlocked!", "Tap to Remove All Small Pets"],
        brush: "Brush",
        brush_info_1: "Tap to remove small animals",
        brush_info_2: "Clear all animals smaller than Hedgehog!",
        brush_info_3: "There's nothing to clear with brush",
        flavour_1: "Pawradise!",
        flavour_2: "Purrfection!",
        flavour_3: "Meowgic!",
        flavour_4: "Furrbulous!",
        flavour_5: "Animaltastic!",
        flavour_6: "Pawsome!",
        flavour_7: "Finomenal!",
        insufficient_coins: "INSUFFICIENT COINS",
        open_exclamation: "OPEN!",
        coins: "Coins",
        tickets: "Tickets",
        popular: "Popular!",
        best_value: "Best Value!",
        free_coins: "Free Coins!",
        get: "Get",
        purchase_successful: ["Purchase", "Successful!"],
        ready_in: "Ready In",
        settings: "SETTINGS",
        music: "Music",
        sound: "Sound",
        vibrate: "Vibrate",
        exit: "Exit",
        support: "Support",
        daily_bonus: "DAILY BONUS",
        day: "Day <X>",
        double_claim: "Double Claim",
        game_over: "GAME OVER!",
        your_score: "Your Score",
        new_high_score: "New High Score",
        remove_small_animals: "Remove Small Animals",
        remove_animals_on_top: "Remove Animals on Top",
        no_thanks: "No Thanks",
        classic_mode: "CLASSIC MODE",
        tuto_classic_info_1: ["Play", "Endless", "and", "Merge", "as Long as You Can!"],
        tuto_classic_info_2: ["Tap", "Home", "to go to", "Classic Mode"],
        tuto_classic_info_3: ["Almost There!", "Tap", "Play Classic"],
        lets_try: "Let's Try!",
        continue_to_next_level: "Continue to Next Level",
        next_level : "Next Level",
        no_ads_available : "No Ads Available",
        adventure_mini_map : "Adventure Map",
        next : "Next",
        offer : "OFFER",
        limited_offer: "LIMITED OFFER",
        discount: "SAVE"
    },
    id: {
        title: "Pet Merge",
        loading: "Loading",
        high_score: "High Score",
        play: "MAINKAN",
        classic: "Mode Klasik",
        adventure: "Mode Petualangan",
        coming_soon: "Segera Hadir",
        unlock_level: "Buka \n Level <X>",
        star_jar: "Star Jar",
        desc_star_jar: "Mainkan Level, Kumpulkan Bintang, \n dan Buka Star Jar ini!",
        full: "PENUH!",
        rewards: "HADIAH UNTUKMU!",
        open: "BUKA",
        claim: "Ambil",
        tuto_tap_anywhere: "Ketuk untuk Melanjutkan",
        tuto_control: ["Geser", "dan", "Lepas", "\n untuk Jatuhkan Hewan"],
        tuto_adv: ["Selesaikan", "Target", "sebelum", "Sisa Langkah Habis!"],
        tuto_adv_1: ["Jatuhkan", "Hewan untuk", "Dorong", "Hewan lainnya"],
        level: "Level <X>",
        level_short: "Level",
        moves: "Sisa Langkah",
        goals: "Target",
        great: "HEBAT",
        completed: "SELESAI!",
        victory: "BERHASIL!",
        continue: "Lanjutkan",
        continue_question: "LANJUTKAN?",
        get_moves: "Tambah 15 langkah",
        level_failed: "LEVEL GAGAL",
        retry: "Coba Lagi",
        home: "Beranda",
        hammer_booster: "Hammer Booster",
        shake_booster: "Shake Booster",
        tornado_booster: "Tornado Booster",
        brush_booster: "Brush Booster",
        rainbow_booster: "Rainbow Booster",
        wood_box: "Wood Box",
        dessert_box: "Dessert Box",
        ice_box: "Ice Box",
        mystery_box: "Mystery Box",
        unlocked: "Terbuka!",
        tuto_hammer_unlocked: ["Hammer Booster", "Didapatkan!", "Ketuk tombol Hammer"],
        tuto_hammer_unlocked_1: ["Level Sulit", "Terbuka!", "Pakai", "Hammer", "untuk Selesaikan Level Lebih Mudah"],
        hammer: "Hammer",
        booster: "Booster",
        hammer_info_1: "Hilangkan dengan Memilih Hewan atau Objek Apapun",
        hammer_info_2: "Hilangkan Hewan atau Objek Apapun",
        hammer_info_3: "Tidak ada yang bisa Dihilangkan dengan Hammer",
        tuto_tornado_unlocked: ["Tornado Booster", "Didapatkan!", "Ketuk Tombol untuk Memanggil Tornado!"],
        tornado: "Tornado",
        start: "Mulai!",
        tornado_info_1: "Satukan Hewan dengan Tornado",
        tornado_info_2: "Satukan Lebih Banyak Hewan dengan Tornado!",
        tornado_info_3: "Tidak Ada Hewan dalam Kotak",
        tuto_shake_unlocked: ["Shake Booster", "Didapatkan!", "Ketuk Tombol Shake"],
        shake: "Shake",
        shake_info_1: "Goyangkan Semua \n Hewan dan Objek",
        shake_info_2: "Goyang Kotak untuk Satukan Lebih Banyak Hewan!",
        shake_info_3: "Tidak Ada Hewan dalam Kotak",
        tuto_rainbow_unlocked: ["Rainbow Booster", "Didapatkan!", "Ketuk Tombol Rainbow"],
        rainbow: "Rainbow",
        rainbow_info_1: "Jatuhkan Rainbow untuk \n Buat Hewan Lebih Besar",
        tuto_wood_box: ["Satukan", "di","       untuk", "", "Menghancurkannya", ""],
        wood_box_info_1: "Satukan di  Wood Box untuk Menghancurkannya",
        tuto_dessert_box: ["Satukan", "di", "Dessert Box", "untuk", "Menghancurkannya", ""],
        dessert_box_info_1: "Satukan di Dessert Box untuk Menghancurkannya",
        tuto_ice_box: ["Satukan", "di", "Ice Box", "dan", "Bebaskan", "\nHewan di Dalamnya"],
        ice_box_info_1: "Satukan di Ice Box dan Bebaskan Hewan di Dalamnya",
        mystery_box_info_1: "Satukan di Mystery Box untuk Keluarkan Hewan",
        level_up: "LEVEL UP",
        ok: "OK",
        tuto_brush_unlocked: ["Brush Booster", "Didapatkan!", "Ketuk Tombol Brush"],
        brush: "Brush",
        brush_info_1: "Ketuk untuk Menghapus Semua Hewan KEcil",
        brush_info_2: "Hilangkan Semua Hewan Lebih Kecil dari Landak!",
        brush_info_3: "Tidak Ada yang Bisa Dihilangkan dengan Brush",
        flavour_1: "Pawradise!",
        flavour_2: "Purrfection!",
        flavour_3: "Meowgic!",
        flavour_4: "Furrbulous!",
        flavour_5: "Animaltastic!",
        flavour_6: "Pawsome!",
        flavour_7: "Finomenal!",
        insufficient_coins: "KOIN TIDAK CUKUP",
        open_exclamation: "BUKA!",
        coins: "Koin",
        tickets: "Skip It's",
        popular: "Popular!",
        best_value: "Best Value!",
        free_coins: "Koin Gratis!",
        get: "Ambil",
        purchase_successful: ["Pembelian", "Berhasil!"],
        ready_in: "Siap dalam",
        settings: "PENGATURAN",
        music: "Musik",
        sound: "Suara",
        vibrate: "Getar",
        exit: "Keluar",
        support: "Bantuan",
        daily_bonus: "BONUS HARIAN",
        day: "Hari <X>",
        double_claim: "Klaim x2",
        game_over: "GAME OVER!",
        your_score: "Your Score",
        new_high_score: "New High Score",
        remove_small_animals: "Hapus Hewan Kecil",
        remove_animals_on_top: "Hilangkan Hewan di Atas",
        no_thanks: "Tidak Perlu",
        classic_mode: "MODE KLASIK",
        tuto_classic_info_1: ["Main", "Tanpa Akhir", "\n dan", "Satukan Hewan", "Sebanyak Mungkin!"],
        tuto_classic_info_2: ["Ketuk", "Beranda", "untuk ke", "Mode Klasik"],
        tuto_classic_info_3: ["Hampir Sampai!", "Ketuk", "Main Klasik"],
        lets_try: "Ayo Coba!",
        continue_to_next_level: "Lanjut ke Level Berikutnya",
        next_level: "Level Berikutnya",
        no_ads_available: "Iklan Tidak Tersedia",
        adventure_mini_map: "Peta Petualangan",
        next: "Berikutnya",
        offer : "OFFER",
        limited_offer: "LIMITED OFFER",
        discount: "SAVE"
    },
    ru: {
        title: "Кафе для питомцев",
        loading: "Загрузка",
        high_score: "Лучший результат",
        play: "ИГРАТЬ",
        classic: "Классика",
        adventure: "Приключение",
        coming_soon: "Скоро будет",
        unlock_level: "Разблокировать уровень <X>",
        star_jar: "Банка звезд",
        desc_star_jar: "Побеждайте в уровнях, чтобы заработать звезды и открыть банку!",
        full: "ПОЛНЫЙ!",
        rewards: "НАГРАДЫ!",
        open: "ОТКРЫТЬ",
        claim: "Получить",
        tuto_tap_anywhere: "Нажмите в любом месте, чтобы продолжить",
        tuto_control: ["Тяните", "чтобы двигать", "Отпустите", "чтобы сбросить"],
        tuto_adv: ["Достигайте", "цели", "в пределах", "лимита ходов"],
        level: "Уровень <X>",
        level_short: "Уро.",
        moves: "Ходы",
        goals: "Цели",
        great: "ОТЛИЧНО",
        completed: "ЗАВЕРШЕНО!",
        victory: "ПОБЕДА!",
        continue: "Продолжить",
        continue_question: "ПРОДОЛЖИТЬ?",
        get_moves: "Получить 15 ходов",
        level_failed: "УРОВЕНЬ ПРОВАЛЕН",
        retry: "Повторить",
        home: "Домой",
        tuto_hammer_unlocked: ["Бустер молоток", "Разблокирован!", "Нажмите, чтобы выбрать молоток"],
        tuto_hammer_unlocked_1: ["Сложный уровень", "Разблокировано!", "Использовать", "Молот", "Чтобы легче пройти уровень"],
        hammer: "Молоток",
        booster: "Бустер",
        hammer_info_1: "Нажмите на животное или реквизит, чтобы удалить его.",
        hammer_info_2: "Убрать животное или реквизит",
        hammer_info_3: "Нечего убирать молотком",
        tuto_shake_unlocked: ["Бустер встряска", "Разблокирован!", "Нажмите, чтобы встряхнуть корзину"],
        shake: "Встряска",
        shake_info_1: "Встряхнуть всех животных и объекты",
        shake_info_2: "Встряхните коробку для большего количества слияний!",
        shake_info_3: "В коробке нет плиток",
        tuto_rainbow_unlocked: ["Бустер радуга", "Разблокирован!", "Нажмите, чтобы выбрать радугу"],
        rainbow: "Радуга",
        rainbow_info_1: "Сбросьте радугу, чтобы вырастить любое животное",
        tuto_wood_box: ["Собирайте", "рядом", "с коробкой", "чтобы", "разбить", "ее"],
        tuto_dessert_box: ["Собирайте", "рядом", "с десертной коробкой", "чтобы", "разбить", "ее"],
        tuto_ice_box: ["Собирайте", "рядом", "с холодильником", "чтобы", "освободить", "животное"],
        level_up: "УРОВЕНЬ ПОВЫШЕН",
        ok: "Xорошо",
        tuto_brush_unlocked: ["Бустер щетка", "Разблокирован!", "Нажмите, чтобы удалить всех маленьких питомцев"],
        brush: "Щетка",
        brush_info_1: "Нажмите, чтобы удалить маленьких животных",
        brush_info_2: "Уберите всех животных меньше ежика!",
        brush_info_3: "Нечего убирать щеткой",
        flavour_1: "Лапарадиз!",
        flavour_2: "Мурррфектно!",
        flavour_3: "Мяугик!",
        flavour_4: "шумный!",
        flavour_5: "Животнастично!",
        flavour_6: "классный!",
        flavour_7: "Финоменаль!",
        insufficient_coins: "НЕДОСТАТОЧНО МОНЕТ",
        open_exclamation: "ОТКРЫТЬ!",
        coins: "Монеты",
        tickets: "Билеты",
        popular: "Популярно!",
        best_value: "Лучшая ценность!",
        free_coins: "Бесплатные монеты!",
        get: "Получить",
        purchase_successful: ["Покупка", "успешна!"],
        ready_in: "Готово через",
        settings: "НАСТРОЙКИ",
        music: "Музыка",
        sound: "Звук",
        vibrate: "Вибрация",
        exit: "Выход",
        support: "Поддержка",
        daily_bonus: "ЕЖЕДНЕВНЫЙ БОНУС",
        day: "День <X>",
        double_claim: "Двойное получение",
        game_over: "ИГРА ОКОНЧЕНА!",
        your_score: "Ваш счет",
        new_high_score: "Новый рекорд",
        remove_small_animals: "Удалить маленьких животных",
        no_thanks: "Нет, спасибо",
        offer : "ПРЕДЛОЖЕНИЕ",
        limited_offer: "ОГРАНИЧЕННОЕ ПРЕДЛОЖЕНИЕ",
        discount: "СЭКОНОМЬТЕ"
    }
};