// Language content dictionary
export const translations = {
    en: {
        title: "Pet Merge",
        loading: "Loading",
        high_score: "High Score",
        play: "PLAY",
        classic: "Classic",
        adventure: "Adventure",
        coming_soon: "Coming Soon",
        unlock_level: "Unlock Level <X>",
        star_jar: "Star Jar",
        desc_star_jar: "Win levels to earn stars and unlock the jar!",
        full: "FULL!",
        rewards: "REWARDS!",
        open: "OPEN",
        claim: "Claim",
        tuto_tap_anywhere: "Tap to Continue",
        tuto_control: ["Drag","to Move","Release","to Drop"],
        tuto_adv: ["Reach", "the goal", "within", "the move limit"],
        tuto_adv_1: ["Drop", "tiles to", "Push", "others around"],
        level: "Level <X>",
        level_short : "Level",
        moves: "Moves",
        goals: "Goals",
        great: "GREAT",
        completed: "COMPLETED!",
        victory: "VICTORY!",
        continue: "Continue",
        continue_question: "CONTINUE?",
        get_moves: "Get 15 Moves",
        level_failed: "LEVEL FAILED",
        retry: "Retry",
        home: "Home",
        tuto_hammer_unlocked: ["Hammer Booster", "Unlocked!", "Tap to Select Hammer"],
        tuto_hammer_unlocked_1: ["Hard Level", "Unlocked!", "Use", "Hammer", "to Clear Level Easier"],
        hammer: "Hammer",
        booster: "Booster",
        hammer_info_1: "Tap an Animal or Props to Remove it",
        hammer_info_2: "Remove an Animal or Props",
        hammer_info_3: "There's nothing to clear with hammer",
        tuto_shake_unlocked: ["Shake Booster", "Unlocked!", "Tap to Shake the Basket"],
        shake: "Shake",
        shake_info_1: "Shake all animals and objects",
        shake_info_2: "Shake the Box for more merges!",
        shake_info_3: "There's no tile inside the box",
        tuto_rainbow_unlocked: ["Rainbow Booster", "Unlocked!", "Tap to Select Rainbow"],
        rainbow: "Rainbow",
        rainbow_info_1: "Drop rainbow to grow any animal",
        tuto_wood_box: ["Merge", "next", "to       ", "to", "Break", "it"],
        tuto_dessert_box: ["Merge", "next", "to a Dessert Box", "to", "Break", "it"],
        tuto_ice_box: ["Merge", "next", "to an Ice Box", "to", "Free", "the Animal"],
        level_up: "LEVEL UP",
        ok: "OK",
        tuto_brush_unlocked: ["Brush Booster", "Unlocked!", "Tap to Remove All Small Pets"],
        brush: "Brush",
        brush_info_1: "Tap to remove small animals",
        brush_info_2: "Clear all animals smaller than Hedgehog!",
        brush_info_3: "There's nothing to clear with brush",
        flavour_1: "Pawradise!",
        flavour_2: "Purrfection!",
        flavour_3: "Meowgic!",
        flavour_4: "Furrbulous!",
        flavour_5: "Animaltastic!",
        flavour_6: "Pawsome!",
        flavour_7: "Finomenal!",
        insufficient_coins: "INSUFFICIENT COINS",
        open_exclamation: "OPEN!",
        coins: "Coins",
        tickets: "Tickets",
        popular: "Popular!",
        best_value: "Best Value!",
        free_coins: "Free Coins!",
        get: "Get",
        purchase_successful: ["Purchase", "Successful!"],
        ready_in: "Ready In",
        settings: "SETTINGS",
        music: "Music",
        sound: "Sound",
        vibrate: "Vibrate",
        exit: "Exit",
        support: "Support",
        daily_bonus: "DAILY BONUS",
        day: "Day <X>",
        double_claim: "Double Claim",
        game_over: "GAME OVER!",
        your_score: "Your Score",
        new_high_score: "New High Score",
        remove_small_animals: "Remove Small Animals",
        no_thanks: "No Thanks",
        classic_mode: "CLASSIC MODE",
        tuto_classic_info_1: ["Play", "Endless", "and", "Merge", "as Long as You Can!"],
        tuto_classic_info_2: ["Tap", "Home", "to go to", "Classic Mode"],
        tuto_classic_info_3: ["Almost There!", "Tap", "Play Classic"],
        lets_try: "Let's Try!",
        continue_to_next_level: "Continue to Next Level",
        next_level : "Next Level"
        },
    ru: {
        title: "Кафе для питомцев",
        loading: "Загрузка",
        high_score: "Лучший результат",
        play: "ИГРАТЬ",
        classic: "Классика",
        adventure: "Приключение",
        coming_soon: "Скоро будет",
        unlock_level: "Разблокировать уровень <X>",
        star_jar: "Банка звезд",
        desc_star_jar: "Побеждайте в уровнях, чтобы заработать звезды и открыть банку!",
        full: "ПОЛНЫЙ!",
        rewards: "НАГРАДЫ!",
        open: "ОТКРЫТЬ",
        claim: "Получить",
        tuto_tap_anywhere: "Нажмите в любом месте, чтобы продолжить",
        tuto_control: ["Тяните", "чтобы двигать", "Отпустите", "чтобы сбросить"],
        tuto_adv: ["Достигайте", "цели", "в пределах", "лимита ходов"],
        level: "Уровень <X>",
        level_short: "Уро.",
        moves: "Ходы",
        goals: "Цели",
        great: "ОТЛИЧНО",
        completed: "ЗАВЕРШЕНО!",
        victory: "ПОБЕДА!",
        continue: "Продолжить",
        continue_question: "ПРОДОЛЖИТЬ?",
        get_moves: "Получить 15 ходов",
        level_failed: "УРОВЕНЬ ПРОВАЛЕН",
        retry: "Повторить",
        home: "Домой",
        tuto_hammer_unlocked: ["Бустер молоток", "Разблокирован!", "Нажмите, чтобы выбрать молоток"],
        tuto_hammer_unlocked_1: ["Сложный уровень", "Разблокировано!", "Использовать", "Молот", "Чтобы легче пройти уровень"],
        hammer: "Молоток",
        booster: "Бустер",
        hammer_info_1: "Нажмите на животное или реквизит, чтобы удалить его.",
        hammer_info_2: "Убрать животное или реквизит",
        hammer_info_3: "Нечего убирать молотком",
        tuto_shake_unlocked: ["Бустер встряска", "Разблокирован!", "Нажмите, чтобы встряхнуть корзину"],
        shake: "Встряска",
        shake_info_1: "Встряхнуть всех животных и объекты",
        shake_info_2: "Встряхните коробку для большего количества слияний!",
        shake_info_3: "В коробке нет плиток",
        tuto_rainbow_unlocked: ["Бустер радуга", "Разблокирован!", "Нажмите, чтобы выбрать радугу"],
        rainbow: "Радуга",
        rainbow_info_1: "Сбросьте радугу, чтобы вырастить любое животное",
        tuto_wood_box: ["Собирайте", "рядом", "с коробкой", "чтобы", "разбить", "ее"],
        tuto_dessert_box: ["Собирайте", "рядом", "с десертной коробкой", "чтобы", "разбить", "ее"],
        tuto_ice_box: ["Собирайте", "рядом", "с холодильником", "чтобы", "освободить", "животное"],
        level_up: "УРОВЕНЬ ПОВЫШЕН",
        ok: "Xорошо",
        tuto_brush_unlocked: ["Бустер щетка", "Разблокирован!", "Нажмите, чтобы удалить всех маленьких питомцев"],
        brush: "Щетка",
        brush_info_1: "Нажмите, чтобы удалить маленьких животных",
        brush_info_2: "Уберите всех животных меньше ежика!",
        brush_info_3: "Нечего убирать щеткой",
        flavour_1: "Лапарадиз!",
        flavour_2: "Мурррфектно!",
        flavour_3: "Мяугик!",
        flavour_4: "шумный!",
        flavour_5: "Животнастично!",
        flavour_6: "классный!",
        flavour_7: "Финоменаль!",
        insufficient_coins: "НЕДОСТАТОЧНО МОНЕТ",
        open_exclamation: "ОТКРЫТЬ!",
        coins: "Монеты",
        tickets: "Билеты",
        popular: "Популярно!",
        best_value: "Лучшая ценность!",
        free_coins: "Бесплатные монеты!",
        get: "Получить",
        purchase_successful: ["Покупка", "успешна!"],
        ready_in: "Готово через",
        settings: "НАСТРОЙКИ",
        music: "Музыка",
        sound: "Звук",
        vibrate: "Вибрация",
        exit: "Выход",
        support: "Поддержка",
        daily_bonus: "ЕЖЕДНЕВНЫЙ БОНУС",
        day: "День <X>",
        double_claim: "Двойное получение",
        game_over: "ИГРА ОКОНЧЕНА!",
        your_score: "Ваш счет",
        new_high_score: "Новый рекорд",
        remove_small_animals: "Удалить маленьких животных",
        no_thanks: "Нет, спасибо"
    }
};